"""m175 regression against fixtures generated by original ARM64 crypto."""
import json
from pathlib import Path
import unittest

from mtgsig.m175_codec import decode_m175, encode_m175, encode_payload


class M175CodecTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.vectors = json.loads((Path(__file__).parent / "fixtures/m175_vectors.json").read_text())["vectors"]

    def test_original_native_vectors(self):
        for vector in self.vectors:
            with self.subTest(name=vector["name"]):
                self.assertEqual(encode_m175(**vector["inputs"]), vector["native_m175"])
                self.assertEqual(decode_m175(vector["native_m175"]).payload, vector["payload"])

    def test_reencrypt_preserves_original_json_serialization(self):
        payload = ' {"b":"1", "a":"model"} {"m":"设备\\/name","n":"model","o":"iOS","p":"0","q":"1x2","r":"1"}'
        # Native JSON starts at byte zero; preserve spacing and escaping within.
        payload = payload.lstrip()
        encoded = encode_payload(payload)
        self.assertEqual(decode_m175(encoded).payload, payload)
        self.assertEqual(encode_payload(decode_m175(encoded).payload), encoded)

    def test_detects_ciphertext_modification(self):
        encoded = self.vectors[0]["native_m175"]
        for offset in (0, 32, len(encoded) - 2):
            changed = encoded[:offset] + ("00" if encoded[offset:offset + 2] != "00" else "01") + encoded[offset + 2:]
            with self.subTest(offset=offset), self.assertRaises(ValueError):
                decode_m175(changed)

    def test_rejects_invalid_ciphertext(self):
        for value in (None, "", "00", "G" * 32, "00 " * 32, "00" * 16):
            with self.subTest(value=value), self.assertRaises(ValueError):
                decode_m175(value)

    def test_rejects_conflicting_repeated_values(self):
        for payload in ('{"a":"model","b":"1"}{"m":"name","n":"other","o":"os","p":"0","q":"screen","r":"1"}',
                        '{"a":"model","b":"1"}{"m":"name","n":"model","o":"os","p":"0","q":"screen","r":"2"}'):
            with self.assertRaisesRegex(ValueError, "disagree"):
                encode_payload(payload)

    def test_rejects_wrong_schema(self):
        for payload in ('{}{}', '[]{}', '{"a":"x","b":1}{}', '{}', '{}{} trailing'):
            with self.subTest(payload=payload), self.assertRaises(ValueError):
                encode_payload(payload)

    def test_rejects_invalid_profile_inputs(self):
        for field, value in (("timestamp_ms", True), ("timestamp_ms", -1),
                             ("timestamp_ms", 1.5), ("model", 12), ("device_name", [])):
            inputs = dict(self.vectors[0]["inputs"], **{field: value})
            with self.subTest(field=field, value=value), self.assertRaises(ValueError):
                encode_m175(**inputs)


if __name__ == "__main__":
    unittest.main()
